<a href="https://colab.research.google.com/github/jimmiychen/ML100Days/blob/main/Python%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%A8%8B%E5%BC%8F%E9%A6%AC%E6%8B%89%E6%9D%BE_D2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[簡答題] 1.請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？**


In [4]:
import numpy as np
a=np.arange(15).reshape(3,5)

print("法一:type(a):", type(a))    
print("法二:a.dtype:", a.dtype)  

法一:type(a): <class 'numpy.ndarray'>
法二:a.dtype: int64


Ans:
1.   法一:type(a)：顯示Array在numpy中之type
2.   法二:a.dtype：顯示Array元素之data type

# **2.請撰寫一個判斷 a 的元素是否等於指定資料型態的函式**

In [20]:
import numpy as np
a=np.arange(8).reshape(2,4)

def is_dtype(a,type):
  return a.dtype is np.dtype(type)

print("法一:",is_dtype(a,'int64'))
print("法二:",is_dtype(a,np.int))
print("法三:",is_dtype(a,np.dtype('int')))


法一: True
法二: True
法三: True


# **3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。**

In [ ]:
import numpy as np
#a=np.arange(30).reshape(5,3,2)
#a = np.random.randint(10, size=6) 

print("==========================")
a = np.random.randint(10, size=6) 
print("法一:tolist():", a.tolist()) 
print("法二:list(a):", list(a))    
print("\n") 

print("==========================")
b = np.random.randint(10, size=(3,4))
print("法一:tolist():", b.tolist())  
print("法二:list(b):", list(b))    
print("\n") 

print("==========================")
c = np.random.randint(10, size=(2,3,2))
print("法一:tolist():", c.tolist()) 
print("法二:list(c):", list(c))    
print("\n") 

def list_append(test_array):
  if(test_array)!=np.ndarray:
    return test_array
  else:
    new_array=[]
    for obj in test_array:
      new_array.append(tolist(test_array))
    return list(new_array)


print("==========================")
print("法一:tolist():", a.tolist()) 
print("法二:list(a):", list(a))    
print("法三:list_append展開--->list_append(a):", list_append(a)) 
print("\n") 

print("==========================")
print("法一:tolist():", b.tolist()) 
print("法二:list(b):", list(b))    
print("法三:list_append展開--->list_append(b):", list_append(b)) 
print("\n") 

print("==========================")
print("法一:tolist():", c.tolist()) 
print("法二:list(c):", list(c))    
print("法三:list_append展開--->list_append(c):", list_append(c)) 
print("\n") 


法一:tolist(): [7, 5, 3, 9, 0, 3]
法二:list(a): [7, 5, 3, 9, 0, 3]


法一:tolist(): [[4, 7, 4, 4], [2, 5, 1, 9], [0, 9, 9, 3]]
法二:list(b): [array([4, 7, 4, 4]), array([2, 5, 1, 9]), array([0, 9, 9, 3])]


法一:tolist(): [[[1, 8], [0, 4], [7, 1]], [[3, 4], [2, 8], [1, 0]]]
法二:list(c): [array([[1, 8],
       [0, 4],
       [7, 1]]), array([[3, 4],
       [2, 8],
       [1, 0]])]


法一:tolist(): [7, 5, 3, 9, 0, 3]
法二:list(a): [7, 5, 3, 9, 0, 3]
法三:list_append展開--->list_append(a): [7 5 3 9 0 3]


法一:tolist(): [[4, 7, 4, 4], [2, 5, 1, 9], [0, 9, 9, 3]]
法二:list(b): [array([4, 7, 4, 4]), array([2, 5, 1, 9]), array([0, 9, 9, 3])]
法三:list_append展開--->list_append(b): [[4 7 4 4]
 [2 5 1 9]
 [0 9 9 3]]


法一:tolist(): [[[1, 8], [0, 4], [7, 1]], [[3, 4], [2, 8], [1, 0]]]
法二:list(c): [array([[1, 8],
       [0, 4],
       [7, 1]]), array([[3, 4],
       [2, 8],
       [1, 0]])]
法三:list_append展開--->list_append(c): [[[1 8]
  [0 4]
  [7 1]]

 [[3 4]
  [2 8]
  [1 0]]]




/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


Ans:

   利用for迴圈逐層對Array使用list(...)展開,即可達到a.tolist之效果

