<a href="https://colab.research.google.com/github/jimmiychen/ML100Days/blob/main/Python%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%A8%8B%E5%BC%8F%E9%A6%AC%E6%8B%89%E6%9D%BE_D5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。**


In [18]:
import numpy as np

a=np.arange(11)+1
print("原來:",a)
#with loop
for i in range(0,len(a)):
  if a[i]>=3 and a[i]<=6:
    a[i]=-a[i]
print("後來:",a)


原來: [ 1  2  3  4  5  6  7  8  9 10 11]
後來: [ 1  2 -3 -4 -5 -6  7  8  9 10 11]


# **2.試著從一個隨機陣列中，找出比 0.5 大的數有幾個？。**

In [19]:
import numpy as np

a=np.random.rand(3,6)
b=np.full((3,6),0.5)  #指定Array所有值都是0.5

print(a)
print(b)

c=a>b
print(c)
sum1=np.sum(c)
print("法一:",sum1)

sum2=np.sum(a>0.5)
print("法二:",sum2)

#對象：NumPy數組或矩陣，eg. data的元素為True和False
#numpy.sum（data）　　　　　　　　      #統計data中True的個數
#numpy.count_nonzero（data）　　       #統計data中True的個數

#對象：NumPy數組或矩陣，eg. data的元素為數值
#numpy.sum（data==0.2）　　　　　　　　   #統計data中數值為0.2的個數
#numpy.count_nonzero（data==0.2）　　    #統計data中數值為0.2的個數
#numpy.sum（data<0.2）　　　　　　　　    #統計data中數值小於0.2的個數
#numpy.count_nonzero（data<0.2）　　     #統計data中數值小於0.2的個數


[[0.51393772 0.91497019 0.0859603  0.75227259 0.92415287 0.95747537]
 [0.3755492  0.86030112 0.00199226 0.66770722 0.27102292 0.45216188]
 [0.54491068 0.33605808 0.62746664 0.65082505 0.43913015 0.90335624]]
[[0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]]
[[ True  True False  True  True  True]
 [False  True False  True False False]
 [ True False  True  True False  True]]
法一: 11
法二: 11
