<a href="https://colab.research.google.com/github/jimmiychen/ML100Days/blob/main/Python%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%A8%8B%E5%BC%8F%E9%A6%AC%E6%8B%89%E6%9D%BE_D6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.[簡答題] 請問下列這三種方法有什麼不同？**
print(a.sum())
print(np.sum(a))
print(sum(a)) 


In [3]:
import numpy as np

a=np.arange(5)
print("a=",a)
print(a.sum())
print(np.sum(a)) #較好
print(sum(a))
print("三種都一樣")


a= [0 1 2 3 4]
10
10
10
三種都一樣


# **2.請對一個 5x5 的隨機矩陣作正規化的操作。。**

In [14]:
import numpy as np

a=np.random.rand(5,5)
print(a)
print("\n")
print("Mean Function:", np.mean(a))
print("Std Function:", np.std(a))
b=(a-np.mean(a))/np.std(a)
print("\n")
print("Normalized: ",b)



[[0.40331318 0.75498566 0.82814349 0.07651285 0.15397658]
 [0.30374471 0.26544856 0.53820183 0.85260374 0.06203435]
 [0.46376467 0.24795239 0.78968593 0.34285282 0.7957117 ]
 [0.55230242 0.89711554 0.01292079 0.13025868 0.33283374]
 [0.53699842 0.35701527 0.53565976 0.75305906 0.25074106]]


Mean Function: 0.4495134879341192
Std Function: 0.26840402608966735


Normalized:  [[-0.17212971  1.13810577  1.41067184 -1.38969836 -1.10108969]
 [-0.54309461 -0.6857756   0.33042851  1.50180404 -1.4436413 ]
 [ 0.05309602 -0.75096151  1.26738948 -0.39738847  1.28983985]
 [ 0.38296344  1.66764285 -1.626625   -1.18945612 -0.43471684]
 [ 0.32594495 -0.34462306  0.32095746  1.13092778 -0.74057171]]


# **3.請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。**

In [21]:
import numpy as np

a=np.random.rand(10)
print("原來\n ",a)
a[np.argmax(a)]=-1
print("後來\n " ,a)


原來
  [0.37322184 0.23978565 0.58501686 0.92182427 0.93765545 0.53113267
 0.43084125 0.78254438 0.15655309 0.77912887]
後來
  [ 0.37322184  0.23978565  0.58501686  0.92182427 -1.          0.53113267
  0.43084125  0.78254438  0.15655309  0.77912887]
