<a href="https://colab.research.google.com/github/jimmiychen/ML100Days/blob/main/Python%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%A8%8B%E5%BC%8F%E9%A6%AC%E6%8B%89%E6%9D%BE_D6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.[簡答題] 請問下列這三種方法有什麼不同？**
print(a.sum())
print(np.sum(a))
print(sum(a)) 


In [ ]:
import numpy as np

a=np.arange(5)
print("a=",a)
print(a.sum())
print(np.sum(a)) #較好
print(sum(a))
print("三種都一樣")


a= [0 1 2 3 4]
10
10
10
三種都一樣


# **2.請對一個 5x5 的隨機矩陣作正規化的操作。**

In [2]:
import numpy as np

a=np.random.rand(5,5)
print(a)
print("\n")
print("Mean Function:", np.mean(a))
print("Std Function:", np.std(a))
b=(a-np.mean(a))/np.std(a)
print("\n")
print("Normalized: ",b)



[[0.45643386 0.96648988 0.67387963 0.56889404 0.30336503]
 [0.85009966 0.2880699  0.36487152 0.80993922 0.7406328 ]
 [0.75711996 0.86036785 0.43854277 0.87288392 0.92190652]
 [0.30707547 0.03018153 0.26734896 0.90919784 0.04717229]
 [0.13325449 0.13865926 0.89119625 0.06055002 0.77709988]]


Mean Function: 0.5374093030364326
Std Function: 0.3154207891975751


Normalized:  [[-0.25672196  1.36034338  0.43266118  0.0998182  -0.74200649]
 [ 0.99134351 -0.79049767 -0.54700827  0.86402015  0.64429329]
 [ 0.69656364  1.02389746 -0.31344329  1.06357802  1.21899772]
 [-0.73024303 -1.60809873 -0.85619068  1.17870651 -1.55423177]
 [-1.28131953 -1.26418439  1.12163484 -1.51181946  0.75990737]]


# **3.請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。**

In [ ]:
import numpy as np

a=np.random.rand(10)
print("原來\n ",a)
a[np.argmax(a)]=-1
print("後來\n " ,a)


原來
  [0.37322184 0.23978565 0.58501686 0.92182427 0.93765545 0.53113267
 0.43084125 0.78254438 0.15655309 0.77912887]
後來
  [ 0.37322184  0.23978565  0.58501686  0.92182427 -1.          0.53113267
  0.43084125  0.78254438  0.15655309  0.77912887]
