<a href="https://colab.research.google.com/github/jimmiychen/ML100Days/blob/main/Python%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%A8%8B%E5%BC%8F%E9%A6%AC%E6%8B%89%E6%9D%BE_D4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[簡答題] 1.請問下列程式碼，運算結果分別為何？**


In [2]:
import numpy as np

a=np.array([20,30,40,50])
b=np.array([1,2,3,4]) 
c=1
d=np.array([1])
e=np.array([1,2]) 

print(a+a)  #[40,60,80,100]
print(a+b)  #[21,32,43,54]
print(a+c)  #[21,31,41,51]
print(a+d)  #[21,31,41,51]
print(a+e)  #error 

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: ignored

Ans:
1.   Array a 自己加自己
2.   Array a 加 Array b
3.   Array a 加 1 (廣播)
4.   同上，Array a 加 1 (廣播)
5.   維度不同，無法相加，故出現錯誤

# **2.如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？。**

In [36]:
import numpy as np

a=np.ones(3)*1
b=np.ones(3)*2

#without loop
c=[]
c=(a+b)*(-a/2)
print("不用迴圈",c)

#with loop
d=np.empty(3)
for i in range(0,a.shape[0]):
    d[i]=(a[i]+b[i])*(-a[i]/2)

print("用迴圈  ",d)

不用迴圈 [-1.5 -1.5 -1.5]
用迴圈   [-1.5 -1.5 -1.5]


# **3.請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？。**

In [38]:
import numpy as np

a=np.ones((1,6))
b=np.ones((6,1))

print("外積",a*b)
print("\n")
print("內積",a@b)


外積 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


內積 [[6.]]
