<a href="https://colab.research.google.com/github/jimmiychen/ML100Days/blob/main/Python%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%A8%8B%E5%BC%8F%E9%A6%AC%E6%8B%89%E6%9D%BE_D1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[簡答題] 1.請問下列兩種將 Array 轉換成 List 的方式有何不同？**


In [ ]:
import numpy as np
a=np.arange(15).reshape(3,5)
print("法一:list(a):", list(a))    
print("法二:tolist():", a.tolist())  

法一:list(a): [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
法二:tolist(): [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


Ans:
1.   法一:Array採用List轉換：只做到第1層之轉換
2.   法二:Array採用tolist轉換：可做到各層巢狀之轉換

# **2.請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）**

In [ ]:
import numpy as np
#a=np.arange(30).reshape(5,3,2)
#a = np.random.randint(10, size=6) 

print("==========================")
a = np.random.randint(10, size=6) 
print("ndim=",a.ndim)
print("shape=",a.shape)
print("size=",a.size)
print("dtype=",a.dtype)
print("itemsize=",a.itemsize)
print("length=",len(a))
print("type=",type(a))

print("==========================")
b = np.random.randint(10, size=(3,4)) 
print("ndim=",b.ndim)
print("shape=",b.shape)
print("size=",b.size)
print("dtype=",b.dtype)
print("itemsize=",b.itemsize)
print("length=",len(b))
print("type=",type(b))

print("==========================")
c = np.random.randint(10, size=(2,3,2))
print("ndim=",c.ndim)
print("shape=",c.shape)
print("size=",c.size)
print("dtype=",c.dtype)
print("itemsize=",c.itemsize)
print("length=",len(c))
print("type=",type(c))
print("==========================")

ndim= 1
shape= (6,)
size= 6
dtype= int64
itemsize= 8
length= 6
type= <class 'numpy.ndarray'>
ndim= 2
shape= (3, 4)
size= 12
dtype= int64
itemsize= 8
length= 3
type= <class 'numpy.ndarray'>
ndim= 3
shape= (2, 3, 2)
size= 12
dtype= int64
itemsize= 8
length= 2
type= <class 'numpy.ndarray'>


Ans:
1.   ndim    :顯示Array是多少維度
2.   shape   :顯示Array各個維度的元素個數
3.   size    :顯示Array元素個數總和
4.   dtype   :顯示Array元素之datatype
5.   itemsize  :顯示Array元素所佔byte數
6.   length   :顯示Array第一個維度的元素個數
7.   type    :顯示Array在numpy中之type


# **3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。**

In [10]:
import numpy as np
#a=np.arange(30).reshape(5,3,2)
#a = np.random.randint(10, size=6) 

print("==========================")
a = np.random.randint(10, size=6) 
print("法一:tolist():", a.tolist()) 
print("法二:list(a):", list(a))    
print("\n") 

print("==========================")
b = np.random.randint(10, size=(3,4))
print("法一:tolist():", b.tolist())  
print("法二:list(b):", list(b))    
print("\n") 

print("==========================")
c = np.random.randint(10, size=(2,3,2))
print("法一:tolist():", c.tolist()) 
print("法二:list(c):", list(c))    
print("\n") 

def list_append(test_array):
  if(test_array)!=np.ndarray:
    return test_array
  else:
    new_array=[]
    for obj in test_array:
      new_array.append(tolist(test_array))
    return list(new_array)


print("==========================")
print("法一:tolist():", a.tolist()) 
print("法二:list(a):", list(a))    
print("法三:list_append展開--->list_append(a):", list_append(a)) 
print("\n") 

print("==========================")
print("法一:tolist():", b.tolist()) 
print("法二:list(b):", list(b))    
print("法三:list_append展開--->list_append(b):", list_append(b)) 
print("\n") 

print("==========================")
print("法一:tolist():", c.tolist()) 
print("法二:list(c):", list(c))    
print("法三:list_append展開--->list_append(c):", list_append(c)) 
print("\n") 


法一:tolist(): [7, 5, 3, 9, 0, 3]
法二:list(a): [7, 5, 3, 9, 0, 3]


法一:tolist(): [[4, 7, 4, 4], [2, 5, 1, 9], [0, 9, 9, 3]]
法二:list(b): [array([4, 7, 4, 4]), array([2, 5, 1, 9]), array([0, 9, 9, 3])]


法一:tolist(): [[[1, 8], [0, 4], [7, 1]], [[3, 4], [2, 8], [1, 0]]]
法二:list(c): [array([[1, 8],
       [0, 4],
       [7, 1]]), array([[3, 4],
       [2, 8],
       [1, 0]])]


法一:tolist(): [7, 5, 3, 9, 0, 3]
法二:list(a): [7, 5, 3, 9, 0, 3]
法三:list_append展開--->list_append(a): [7 5 3 9 0 3]


法一:tolist(): [[4, 7, 4, 4], [2, 5, 1, 9], [0, 9, 9, 3]]
法二:list(b): [array([4, 7, 4, 4]), array([2, 5, 1, 9]), array([0, 9, 9, 3])]
法三:list_append展開--->list_append(b): [[4 7 4 4]
 [2 5 1 9]
 [0 9 9 3]]


法一:tolist(): [[[1, 8], [0, 4], [7, 1]], [[3, 4], [2, 8], [1, 0]]]
法二:list(c): [array([[1, 8],
       [0, 4],
       [7, 1]]), array([[3, 4],
       [2, 8],
       [1, 0]])]
法三:list_append展開--->list_append(c): [[[1 8]
  [0 4]
  [7 1]]

 [[3 4]
  [2 8]
  [1 0]]]




/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


Ans:

   利用for迴圈逐層對Array使用list(...)展開,即可達到a.tolist之效果

