<a href="https://colab.research.google.com/github/jimmiychen/ML100Days/blob/main/Python%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%A8%8B%E5%BC%8F%E9%A6%AC%E6%8B%89%E6%9D%BE_D7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。**


In [25]:
import numpy as np
import time

a=np.random.randint(0,10,1000000).reshape(100,100,100)
b=a
print(a)
print(b)

print("\n")

###########################################
start=time.process_time() #測時間
#法一:廣播+1
print("法一:廣播+1\n",a+1) 
end=time.process_time() #測時間
print("執行時間=",end-start) #測時間
###########################################

print("\n")

###########################################
start=time.process_time() #測時間
#法二:for loop  +1
with np.nditer(b,op_flags=['readwrite']) as iter:   
   for x in iter:
       x[...]=x+1   
print("法二:for loop  +1\n",b)    
end=time.process_time() #測時間
print("執行時間=",end-start)#測時間
###########################################

[[[4 8 4 ... 9 5 9]
  [3 9 7 ... 7 1 4]
  [7 6 9 ... 1 8 4]
  ...
  [1 5 1 ... 4 7 8]
  [9 0 7 ... 5 7 7]
  [0 3 2 ... 6 6 9]]

 [[1 6 8 ... 9 9 2]
  [1 6 2 ... 2 1 1]
  [4 9 6 ... 6 0 3]
  ...
  [9 6 7 ... 5 4 0]
  [7 1 2 ... 8 4 7]
  [8 5 7 ... 5 1 5]]

 [[4 3 3 ... 5 8 8]
  [3 4 8 ... 4 6 5]
  [7 9 5 ... 8 5 6]
  ...
  [3 0 9 ... 1 3 1]
  [3 7 0 ... 1 4 3]
  [0 1 2 ... 4 6 1]]

 ...

 [[8 3 9 ... 5 7 6]
  [2 6 4 ... 7 4 3]
  [8 8 5 ... 3 8 9]
  ...
  [2 3 0 ... 1 4 1]
  [5 6 4 ... 0 1 6]
  [2 9 3 ... 2 3 7]]

 [[9 6 3 ... 7 1 8]
  [6 5 7 ... 5 5 5]
  [7 6 9 ... 6 2 8]
  ...
  [3 6 6 ... 1 7 1]
  [6 6 5 ... 1 4 1]
  [9 6 1 ... 8 5 3]]

 [[1 2 7 ... 1 6 5]
  [4 9 7 ... 8 6 6]
  [9 7 9 ... 8 2 5]
  ...
  [5 8 3 ... 5 1 8]
  [5 8 5 ... 0 5 1]
  [1 3 7 ... 9 8 4]]]
[[[4 8 4 ... 9 5 9]
  [3 9 7 ... 7 1 4]
  [7 6 9 ... 1 8 4]
  ...
  [1 5 1 ... 4 7 8]
  [9 0 7 ... 5 7 7]
  [0 3 2 ... 6 6 9]]

 [[1 6 8 ... 9 9 2]
  [1 6 2 ... 2 1 1]
  [4 9 6 ... 6 0 3]
  ...
  [9 6 7 ... 5 4 0]
  [7 1 2 ...

# **2.如何從一個陣列中，找出出現頻率最高的數值與位置？。**

In [26]:
import numpy as np

a=np.random.randint(0,10,100) #亂數產生100個0~9的數字
count=np.bincount(a)      #統計0~9共發生幾次    
print(a)
print(count)
print("\n")
print("出現頻率最高之數值=",count.argmax())
print("出現頻率=",count[count.argmax()])
print("出現頻率最高之數值位置=",np.where(a==count.argmax()))

[4 5 1 6 4 0 0 3 4 1 1 8 0 5 3 0 3 6 7 3 9 2 9 3 4 1 8 9 6 1 4 5 5 4 1 4 2
 4 0 1 7 2 1 3 8 7 1 9 1 7 9 3 5 2 0 7 8 8 3 6 5 2 4 1 6 9 5 3 1 6 6 3 6 3
 5 3 1 7 0 0 2 8 5 7 7 3 4 4 6 5 9 0 5 4 8 3 4 5 7 5]
[ 9 13  6 14 13 13  9  9  7  7]


出現頻率最高之數值= 3
出現頻率= 14
出現頻率最高之數值位置= (array([ 7, 14, 16, 19, 23, 43, 51, 58, 67, 71, 73, 75, 85, 95]),)


# **3.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。**

In [27]:
import numpy as np
#a=np.arange(30).reshape(5,3,2)
#a = np.random.randint(10, size=6) 

print("==========================")
a = np.random.randint(10, size=6) 
print("法一:tolist():", a.tolist()) 
print("法二:list(a):", list(a))    
print("\n") 

print("==========================")
b = np.random.randint(10, size=(3,4))
print("法一:tolist():", b.tolist())  
print("法二:list(b):", list(b))    
print("\n") 

print("==========================")
c = np.random.randint(10, size=(2,3,2))
print("法一:tolist():", c.tolist()) 
print("法二:list(c):", list(c))    
print("\n") 

def list_append(test_array):
  if(test_array)!=np.ndarray:
    return test_array
  else:
    new_array=[]
    for obj in test_array:
      new_array.append(tolist(test_array))
    return list(new_array)


print("==========================")
print("法一:tolist():", a.tolist()) 
print("法二:list(a):", list(a))    
print("法三:list_append展開--->list_append(a):", list_append(a)) 
print("\n") 

print("==========================")
print("法一:tolist():", b.tolist()) 
print("法二:list(b):", list(b))    
print("法三:list_append展開--->list_append(b):", list_append(b)) 
print("\n") 

print("==========================")
print("法一:tolist():", c.tolist()) 
print("法二:list(c):", list(c))    
print("法三:list_append展開--->list_append(c):", list_append(c)) 
print("\n") 


法一:tolist(): [9, 7, 5, 3, 5, 1]
法二:list(a): [9, 7, 5, 3, 5, 1]


法一:tolist(): [[8, 8, 9, 4], [4, 4, 1, 3], [5, 5, 7, 2]]
法二:list(b): [array([8, 8, 9, 4]), array([4, 4, 1, 3]), array([5, 5, 7, 2])]


法一:tolist(): [[[7, 9], [9, 4], [0, 5]], [[7, 7], [3, 5], [1, 6]]]
法二:list(c): [array([[7, 9],
       [9, 4],
       [0, 5]]), array([[7, 7],
       [3, 5],
       [1, 6]])]


法一:tolist(): [9, 7, 5, 3, 5, 1]
法二:list(a): [9, 7, 5, 3, 5, 1]
法三:list_append展開--->list_append(a): [9 7 5 3 5 1]


法一:tolist(): [[8, 8, 9, 4], [4, 4, 1, 3], [5, 5, 7, 2]]
法二:list(b): [array([8, 8, 9, 4]), array([4, 4, 1, 3]), array([5, 5, 7, 2])]
法三:list_append展開--->list_append(b): [[8 8 9 4]
 [4 4 1 3]
 [5 5 7 2]]


法一:tolist(): [[[7, 9], [9, 4], [0, 5]], [[7, 7], [3, 5], [1, 6]]]
法二:list(c): [array([[7, 9],
       [9, 4],
       [0, 5]]), array([[7, 7],
       [3, 5],
       [1, 6]])]
法三:list_append展開--->list_append(c): [[[7 9]
  [9 4]
  [0 5]]

 [[7 7]
  [3 5]
  [1 6]]]




/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


Ans:

   利用for迴圈逐層對Array使用list(...)展開,即可達到a.tolist之效果