<a href="https://colab.research.google.com/github/jimmiychen/ML100Days/blob/main/Python%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%A8%8B%E5%BC%8F%E9%A6%AC%E6%8B%89%E6%9D%BE_D3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[簡答題] 1.請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？**


In [ ]:
import numpy as np
a=np.zeros(3).reshape(1,3)
b=np.empty(3).reshape(1,3)
print("a:",a)    
print("b:",b)  

a: [[0. 0. 0.]]
b: [[5.e-324 5.e-324 5.e-324]]


Ans:
1.   np.zeros產生預設值為1，且形狀固定之Array
2.   np.empty產生形狀固定之Array，對於預設值則不是那麼在乎，故隨意給定一個很小的值即可
3.   若一開始宣告Array不給定預設值，可能在後續進行運算時,出現不可預期之結果

# **2.在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。**

In [ ]:
import numpy as np

a=np.random.rand(2,3) #產生一個2x3的random Array
a=a*100

a=np.around(a) #numpy中的np.around相當於python的round
print(a)


[[76. 79. 14.]
 [38.  7. 26.]]


# **3.承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。**

In [ ]:
import numpy as np

a=np.random.rand(10,10) #產生一個10x10的random Array
m=0
n=100

a=m+(a*(n-m)) #原來產生0~1之亂數，現在放大n-m倍，並平移m

a=np.around(a) #numpy中的np.around相當於python的round
print(a)


[[ 84.  63.  67.  14.  50. 100.   7.  18.  77.  18.]
 [ 19.  42.  59.  80.  73.  29.  83.   7.  25.  49.]
 [ 40.  64.  14.  39.   3.  61.  89.  42.   9.  48.]
 [ 78.  92.  62.  85.  32.  51.  69.  26.  55.  88.]
 [ 49.  12.  26.  59.  95.  72.  66.  25.  35.  59.]
 [  3.  87.   1.  90.  38.   0.  84.  51.  86.  16.]
 [ 12.   5.  21.  38.  92.  73.  22.  21.  23.  84.]
 [ 58.  89.  66.  99.  70.  42.  44.   7.  91.  58.]
 [ 89.  70.  80.  77.  81.  67.  28.  21.  37.  24.]
 [ 88.  83.  24.  61.  60.  96.  76.  60.  51.  76.]]
